//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.510
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace UIProcessQuickstarts_Store {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class CustomerDS : DataSet {
        
        private CustomersDataTable tableCustomers;
        
        public CustomerDS() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected CustomerDS(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["customer"] != null)) {
                    this.Tables.Add(new CustomersDataTable(ds.Tables["customer"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public CustomersDataTable Customers {
            get {
                return this.tableCustomers;
            }
        }
        
        public override DataSet Clone() {
            CustomerDS cln = ((CustomerDS)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["customer"] != null)) {
                this.Tables.Add(new CustomersDataTable(ds.Tables["customer"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableCustomers = ((CustomersDataTable)(this.Tables["customer"]));
            if ((this.tableCustomers != null)) {
                this.tableCustomers.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "CustomerDS";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/CustomerDS.xsd";
            this.Locale = new System.Globalization.CultureInfo("es-AR");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableCustomers = new CustomersDataTable();
            this.Tables.Add(this.tableCustomers);
        }
        
        private bool ShouldSerializeCustomers() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void CustomerChangeEventHandler(object sender, CustomerChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class CustomersDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnCustomerId;
            
            private DataColumn columnFullName;
            
            private DataColumn columnEmailAddress;
            
            private DataColumn columnPassword;
            
            internal CustomersDataTable() : 
                    base("customer") {
                this.InitClass();
            }
            
            internal CustomersDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn CustomerIdColumn {
                get {
                    return this.columnCustomerId;
                }
            }
            
            internal DataColumn FullNameColumn {
                get {
                    return this.columnFullName;
                }
            }
            
            internal DataColumn EmailAddressColumn {
                get {
                    return this.columnEmailAddress;
                }
            }
            
            internal DataColumn PasswordColumn {
                get {
                    return this.columnPassword;
                }
            }
            
            public Customer this[int index] {
                get {
                    return ((Customer)(this.Rows[index]));
                }
            }
            
            public event CustomerChangeEventHandler CustomerChanged;
            
            public event CustomerChangeEventHandler CustomerChanging;
            
            public event CustomerChangeEventHandler CustomerDeleted;
            
            public event CustomerChangeEventHandler CustomerDeleting;
            
            public void AddCustomer(Customer row) {
                this.Rows.Add(row);
            }
            
            public Customer AddCustomer(int CustomerId, string FullName, string EmailAddress, string Password) {
                Customer rowCustomer = ((Customer)(this.NewRow()));
                rowCustomer.ItemArray = new object[] {
                        CustomerId,
                        FullName,
                        EmailAddress,
                        Password};
                this.Rows.Add(rowCustomer);
                return rowCustomer;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                CustomersDataTable cln = ((CustomersDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new CustomersDataTable();
            }
            
            internal void InitVars() {
                this.columnCustomerId = this.Columns["CustomerID"];
                this.columnFullName = this.Columns["FullName"];
                this.columnEmailAddress = this.Columns["EmailAddress"];
                this.columnPassword = this.Columns["Password"];
            }
            
            private void InitClass() {
                this.columnCustomerId = new DataColumn("CustomerID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCustomerId);
                this.columnFullName = new DataColumn("FullName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFullName);
                this.columnEmailAddress = new DataColumn("EmailAddress", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnEmailAddress);
                this.columnPassword = new DataColumn("Password", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPassword);
                this.columnCustomerId.AllowDBNull = false;
                this.columnFullName.AllowDBNull = false;
                this.columnEmailAddress.AllowDBNull = false;
                this.columnPassword.AllowDBNull = false;
            }
            
            public Customer NewCustomer() {
                return ((Customer)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new Customer(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(Customer);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.CustomerChanged != null)) {
                    this.CustomerChanged(this, new CustomerChangeEvent(((Customer)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.CustomerChanging != null)) {
                    this.CustomerChanging(this, new CustomerChangeEvent(((Customer)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.CustomerDeleted != null)) {
                    this.CustomerDeleted(this, new CustomerChangeEvent(((Customer)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.CustomerDeleting != null)) {
                    this.CustomerDeleting(this, new CustomerChangeEvent(((Customer)(e.Row)), e.Action));
                }
            }
            
            public void RemoveCustomer(Customer row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class Customer : DataRow {
            
            private CustomersDataTable tableCustomers;
            
            internal Customer(DataRowBuilder rb) : 
                    base(rb) {
                this.tableCustomers = ((CustomersDataTable)(this.Table));
            }
            
            public int CustomerId {
                get {
                    return ((int)(this[this.tableCustomers.CustomerIdColumn]));
                }
                set {
                    this[this.tableCustomers.CustomerIdColumn] = value;
                }
            }
            
            public string FullName {
                get {
                    return ((string)(this[this.tableCustomers.FullNameColumn]));
                }
                set {
                    this[this.tableCustomers.FullNameColumn] = value;
                }
            }
            
            public string EmailAddress {
                get {
                    return ((string)(this[this.tableCustomers.EmailAddressColumn]));
                }
                set {
                    this[this.tableCustomers.EmailAddressColumn] = value;
                }
            }
            
            public string Password {
                get {
                    return ((string)(this[this.tableCustomers.PasswordColumn]));
                }
                set {
                    this[this.tableCustomers.PasswordColumn] = value;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class CustomerChangeEvent : EventArgs {
            
            private Customer eventRow;
            
            private DataRowAction eventAction;
            
            public CustomerChangeEvent(Customer row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public Customer Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
